### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by ppsunrise** [aironashish/Bi-Directional-LSTM-sentences-pairs#1]
Hi Ashish Airon,
your work looks fantastic. It seems that the code can solve the problem about classification of sentence pairs. Would you please provide the data for training and testing? What's the format of the data?
Thanks for you kind read.
Regards,
Jiahuan

**Comment by aironashish** [comment]
Thank you for your interest.
It is mentioned in the write up about the format of the data (ID Label Sentence1 Sentence2)

Regarding dataset, any dataset can be used that contains two sentences and a label.
